### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by viktoriia-shyian** [viktoriia-shyian/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by ianshy** [comment]
[Paul Gauguin](https://artsandculture.google.com/asset/self-portrait-with-a-hat/QgHfJsDIMzxAug)
[Crow in the wheat-land](https://artsandculture.google.com/asset/wheatfield-with-crows-vincent-van-gogh/dwFdD5AMQfpSew)
