### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by viktoriia-shyian** [viktoriia-shyian/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by ianshy** [comment]
Early life
Van Gogh was born on March 30, 1853, to upper middle class parents. He spent his early adulthood working for a firm of art dealers before traveling to The Hague, London and Paris.

He was deeply religious as a younger man and aspired to be a pastor, like his father. He became a teacher in England and then he worked as a missionary in a mining region in Belgium where he sketched people from the local community, and in 1885 painted his first major work The Potato Eaters. His palette then consisted mainly of somber earth tones and showed no sign of the vivid coloration that distinguished his later paintings.

France
In March 1886, he moved to Paris and discovered the French Impressionists. He met many artists including Degas, Toulouse-Lautrec, Pissarro and Gauguin, with whom he became friends. Later, he moved to the south of France and was influenced by the region's strong sunlight. His paintings grew brighter in color, and he developed the unique and highly recognizable style that became fully realized during his stay in Arles in 1888.

Van Gogh invited Gauguin to join him in Arles, but their relationship began to deteriorate. Van Gogh admired Gauguin and desperately wanted to be treated as his equal, but Gauguin was arrogant and domineering, something that often frustrated Van Gogh. They quarreled about art; Van Gogh increasingly feared that Gauguin was going to desert him, and the situation, which Van Gogh described as one of "excessive tension," rapidly headed towards a crisis point. Deeply remorseful, he then cut off part of his own ear.

Mental illness
This incident was the first serious sign of the mental health problems that were to afflict Van Gogh for the remaining days of his life. He spent time in psychiatric hospitals and swung between periods of inertia, depression and incredibly concentrated artistic activity. His work reflected the intense colours and strong light of the countryside around him. On May 9, 1889, he asked to be admitted to the asylum at Saint-Rémy-de Provence, a hospital for the mentally ill. In the year Van Gogh spent at the asylum he worked as much as he had at Arles, producing 150 paintings and hundreds of drawings.

Death
Van Gogh went to Paris on May 17, 1890, to visit his brother, Theo. On the advice of Pissarro, Theo had Vincent go to Auvers, just outside Paris. At first, Van Gogh felt relieved at Auvers, but toward the end of June he experienced fits of temper and often quarreled with Gachet. On July 27, 1890, he shot himself in a lonely field and died, two days later, in the morning of July 29, 1890.

His Brother Theo
The most comprehensive primary source for understanding Van Gogh is the collection of letters between him and his younger brother, art dealer Theo van Gogh. They lay the foundation for most of what is known about his thoughts and beliefs.Theo provided his brother with financial and emotional support. The brother's lifelong friendship, and most of what is known of Vincent's thoughts and theories of art, is recorded in the hundreds of letters exchanged between 1872 and 1890. There are more than 600 from Vincent to Theo, and 40 from Theo to Vincent.

**Comment by viktoriia-shyian** [comment]
Ok
